### ISSUE TITLE
Capitalisation of `'GitHub'`

### ISSUE THREAD

**Issue by JamesNZL** [pumbas600/E-Portfolio#6]
![image](https://github.com/pumbas600/E-Portfolio/assets/44986932/fc85a8e5-61c6-4994-bb1c-89b7e2cacd74)

Should be `'GitHub'` 😉

**Comment by pumbas600** [comment]
Great spotting, thank you!

**Comment by pumbas600** [comment]
I shall fix that when I'm not dying :))

**Comment by JamesNZL** [comment]
:):
